spring:
  application:
    name: springboot-vue3
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/big_event
    username: root
    password: root123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

